# Generated by Django 5.1.3 on 2025-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opcua", "0011_remove_opcuadevice_instrument_handler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opcuadevice",
            name="password",
            field=models.CharField(
                blank=True, default="password", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="opcuadevice",
            name="user",
            field=models.CharField(
                blank=True, default="user", max_length=254, null=True
            ),
        ),
    ]
